# Generated by Django 5.2.8 on 2025-11-12 04:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100, unique=True, verbose_name='지점명')),
                ('location', models.TextField(verbose_name='위치')),
                ('phone', models.CharField(max_length=20, verbose_name='지점 연락처')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.CharField(max_length=100, unique=True, verbose_name='로그인 ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='연락처')),
                ('role', models.CharField(choices=[('Customer', '고객'), ('ThemeManager', '테마 관리자'), ('BranchManager', '지점 관리자'), ('Admin', '총괄 관리자')], default='Customer', max_length=20, verbose_name='역할')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.member', verbose_name='작성자 (Admin)')),
                ('target_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.branch', verbose_name='대상 지점 (전체 공지 시 NULL)')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_time', models.DateTimeField(verbose_name='예약 시간')),
                ('num_of_participants', models.IntegerField(verbose_name='참가 인원')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='최종 결제액')),
                ('status', models.CharField(choices=[('Confirmed', '예약 확정'), ('CheckedIn', '입실 완료'), ('Completed', '이용 완료'), ('Cancelled', '예약 취소'), ('NoShow', '노쇼')], default='Confirmed', max_length=20, verbose_name='예약 상태')),
                ('hint_count', models.IntegerField(default=0, verbose_name='힌트 사용 횟수')),
                ('is_success', models.BooleanField(blank=True, null=True, verbose_name='탈출 성공 여부')),
                ('clear_time', models.IntegerField(blank=True, null=True, verbose_name='클리어 시간 (초)')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.member', verbose_name='예약 회원')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=50, verbose_name='결제 수단')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='결제 금액')),
                ('payment_status', models.CharField(max_length=20, verbose_name='결제 상태')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='결제 시각')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.reservation', verbose_name='관련 예약')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='별점')),
                ('comment', models.TextField(blank=True, verbose_name='리뷰 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.member', verbose_name='작성자')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.reservation', verbose_name='관련 예약')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='테마명')),
                ('genre', models.CharField(max_length=50, verbose_name='장르')),
                ('difficulty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='난이도')),
                ('duration', models.IntegerField(verbose_name='소요 시간 (분)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='기본 가격')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='할인율 (%)')),
                ('description', models.TextField(verbose_name='테마 설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('status', models.CharField(choices=[('Ready', '운영 가능'), ('Maintenance', '점검 중')], default='Ready', max_length=20, verbose_name='테마 상태')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.branch', verbose_name='지점')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField(verbose_name='근무 날짜')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(verbose_name='종료 시간')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.branch', verbose_name='근무 지점')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.member', verbose_name='담당 직원')),
                ('assigned_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.theme', verbose_name='배정 테마')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.theme', verbose_name='예약 테마'),
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_description', models.TextField(verbose_name='문제 설명')),
                ('status', models.CharField(choices=[('Reported', '보고됨'), ('InProgress', '처리 중'), ('Resolved', '해결 완료')], default='Reported', max_length=20, verbose_name='처리 상태')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='보고 시각')),
                ('reported_by_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.member', verbose_name='보고자')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.theme', verbose_name='문제 테마')),
            ],
        ),
    ]
