# Generated by Django 5.2.8 on 2025-11-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_staff',
        ),
    ]
