# Generated by Django 5.2.8 on 2025-11-25 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_remove_member_is_active_remove_member_is_admin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchAssignment",
            fields=[
                ("assignment_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="배정일"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.branch",
                        verbose_name="지점",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="관리자(직원)",
                    ),
                ),
            ],
            options={
                "verbose_name": "지점 소속 관리자 배정",
                "verbose_name_plural": "지점 소속 관리자 배정 목록",
                "unique_together": {("branch", "member")},
            },
        ),
    ]
